apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-deployment
  labels:
    app: restapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: restapi
  template:
    metadata:
      labels:
        app: restapi
    spec:
      containers:
      - name: restapi
        image: viveksinghggits/restapi:prep
        imagePullPolicy: IfNotPresent
        env:
        - name: APIPATH
          valueFrom:
            configMapKeyRef:
              name: restapi-config
              key: APIPATH
        - name: DBHOST
          valueFrom:
            configMapKeyRef:
              name: restapi-config
              key: DBHOST
        - name: DBPASS
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
        ports:
        - containerPort: 8080
